insert into ALBUMS values (1,'black');
insert into SONGS values (1, 'blacks');
insert into SONGS_ON_ALBUMS values (1, 1,1);
insert into ALBUMS values (2,'white');
insert into SONGS values (2, 'white');
insert into SONGS_ON_ALBUMS values (2, 1,2);
insert into SONGS values (3, 'rainbow');
insert into SONGS values (4, 'violet');
insert into SONGS values (5, 'red');
insert into SONGS values (6, 'blue');
insert into SONGS values (7, 'green');
insert into SONGS_ON_ALBUMS values (3, 1,3);
insert into SONGS_ON_ALBUMS values (4, 1,4);
insert into SONGS_ON_ALBUMS values (5, 1,5);
insert into SONGS_ON_ALBUMS values (6, 1,6);
insert into SONGS_ON_ALBUMS values (7, 1,7);
insert into SONGS values (8, 'cucumber');
insert into SONGS values (9, 'brussels');
insert into SONGS values (10, 'carrot');
insert into SONGS values (11, 'potato');
insert into SONGS values (12, 'paprika');
insert into SONGS values (13, 'tomato');
insert into SONGS values (14, 'beans');
insert into SONGS_ON_ALBUMS values (8, 2, 8);
insert into SONGS_ON_ALBUMS values (9, 2, 9);
insert into SONGS_ON_ALBUMS values (10, 2, 10);
insert into SONGS_ON_ALBUMS values (11, 2, 11);
insert into SONGS_ON_ALBUMS values (12, 2, 12);
insert into SONGS_ON_ALBUMS values (13, 2, 13);
insert into SONGS_ON_ALBUMS values (14, 2, 14);